kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.name }}
  replicas: 1
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
      annotations:
        # Roll pods when ConfigMap changes
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      hostNetwork: false
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ .Values.name }}
        image: {{ .Values.image }}
        imagePullPolicy: {{ .Values.pullPolicy }}
        envFrom:
        - configMapRef:
            name: {{ .Values.name }}
        livenessProbe:
          httpGet:
            path: /
            port: {{ .Values.port }}
            scheme: HTTP
          initialDelaySeconds: 5
          timeoutSeconds: 5
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: {{ .Values.port }}
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
        ports:
        - containerPort: {{ .Values.port }}
