name: Release
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  release:
    name: Promote tag
    runs-on: ubuntu-latest
    steps:
      - name: login registry
        run: |
          echo "${OCI_REGISTRY_PASSWD}" | docker login registry.randylabs.cloud \
            -u "${OCI_REGISTRY_USERNAME}" --password-stdin
        env:
          OCI_REGISTRY_USERNAME: ${{ secrets.OCI_REGISTRY_USERNAME }}
          OCI_REGISTRY_PASSWD: ${{ secrets.OCI_REGISTRY_PASSWD }}
      - name: set up buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0
      - name: promoting tag ${{ github.sha }}
        run: |
          ref=${{ github.sha }}
          tag=${GITHUB_REF#refs/tags/}
          tag=${tag#v}
          docker buildx imagetools create --tag \
            registry.randylabs.cloud/randylabs/copyright-abuses:${tag} \
            registry.randylabs.cloud/randylabsdev/copyright-abuses:${ref}
          chartVersion=0.0.0-${ref}
          helm pull oci://registry.randylabs.cloud/randylabsdev/charts/copyright-abuses --version ${chartVersion}
          tar xvf copyright-abuses-${chartVersion}.tgz
          sed -i "s/^version:.*$/version: ${tag}/" copyright-abuses/Chart.yaml
          sed -i "s/^appVersion:.*$/appVersion: ${tag}/" copyright-abuses/Chart.yaml
          helm package copyright-abuses --app-version=${tag} --version=${tag}
          helm push copyright-abuses-${tag}.tgz oci://registry.randylabs.cloud/randylabs/charts
